using System;

namespace Core;

public enum LifeState
{
	Alive,
	Dead,
}
public struct DamageTypes
{
	public static string DMG_GENERIC = "generic";                       // generic damage -- do not use if you want players to flinch and bleed!
	public static string DMG_CRUSH = "crush";                           // crushed by falling or moving object. 
																		// NOTE: It's assumed crush damage is occurring as a result of physics collision, so no extra physics force is generated by crush damage.
																		// DON'T use DMG_CRUSH when damaging entities unless it's the result of a physics collision. You probably want DMG_CLUB instead.
	public static string DMG_BULLET = "bullet";                         // shot
	public static string DMG_SLASH = "slash";                           // cut, clawed, stabbed
	public static string DMG_BURN = "burn";                             // heat burned
	public static string DMG_VEHICLE = "vehicle";                       // hit by a vehicle
	public static string DMG_FALL = "fall";                             // fell too far
	public static string DMG_CLUB = "club";                             // crowbar, punch, headbutt
	public static string DMG_SHOCK = "shock";                           // electric shock
	public static string DMG_SONIC = "sonic";                           // sound pulse shockwave
	public static string DMG_ENERGYBEAM = "energybeam";                 // laser or other high energy beam 
	public static string DMG_PREVENT_PHYSICS_FORCE = "nophysforce";     // Prevent a physics force 
	public static string DMG_NEVERGIB = "nevergib";                     // with this bit OR'd in, no damage type will be able to gib victims upon death
	public static string DMG_ALWAYSGIB = "alwaysgib";                   // with this bit OR'd in, any damage type can be made to gib victims upon death.
	public static string DMG_DROWN = "drown";                           // Drowning


	public static string DMG_PARALYZE = "paralyze";                     // slows affected creature down
	public static string DMG_NERVEGAS = "nervegas";                     // nerve toxins, very bad
	public static string DMG_POISON = "poison";                         // blood poisoning - heals over time like drowning damage
	public static string DMG_RADIATION = "radiation";                   // radiation exposure
	public static string DMG_DROWNRECOVER = "drownrecover";             // drowning recovery
	public static string DMG_ACID = "acid";                             // toxic chemicals or acid burns
	public static string DMG_SLOWBURN = "slowburn";                     // in an oven

	public static string DMG_REMOVENORAGDOLL = "removeonragdoll";       // with this bit OR'd in, no ragdoll will be created, and the target will be quietly removed.
																		// use this to kill an entity that you've already got a server-side ragdoll for

	public static string DMG_PHYSGUN = "physgun";                       // Hit by manipulator. Usually doesn't do any damage.
	public static string DMG_PLASMA = "plasma";                         // Shot by Cremator
	public static string DMG_AIRBOAT = "airboat";                       // Hit by the airboat's gun

	public static string DMG_DISSOLVE = "dissolve";                     // Dissolving!
	public static string DMG_BLAST_SURFACE = "blastsurface";            // A blast on the surface of water that cannot harm things underwater
	public static string DMG_DIRECT = "direct";
	public static string DMG_BUCKSHOT = "buckshot";                     // not quite a bullet. Little, rounder, different.

	public static string DMG_BLAST = "explosion";                       // explosion
}

// this is technically useless for now
/*
public class DamageHelpers
{
	public float Damage { get; set; }
	public float BaseDamage { get; set; } //	the damage amount before skill level adjustments are made, used to get uniform damage forces

	public void AdjustDamageScale( float scale )
	{
		if ( BaseDamage == 0f )
			BaseDamage = Damage;

		Damage = BaseDamage * scale;
	}
}*/

[Obsolete( "DamageInfo.Tags is used instead. See DamageTypes struct for new string references" )]
public enum DamageType
{
	DMG_GENERIC,        // generic damage -- do not use if you want players to flinch and bleed!
	DMG_CRUSH,          // crushed by falling or moving object. 
						// NOTE: It's assumed crush damage is occurring as a result of physics collision, so no extra physics force is generated by crush damage.
						// DON'T use DMG_CRUSH when damaging entities unless it's the result of a physics collision. You probably want DMG_CLUB instead.
	DMG_BULLET,         // shot
	DMG_SLASH,          // cut, clawed, stabbed
	DMG_BURN,           // heat burned
	DMG_VEHICLE,        // hit by a vehicle
	DMG_FALL,           // fell too far
	DMG_CLUB,           // crowbar, punch, headbutt
	DMG_SHOCK,          // electric shock
	DMG_SONIC,          // sound pulse shockwave
	DMG_ENERGYBEAM,     // laser or other high energy beam 
	DMG_PREVENT_PHYSICS_FORCE,  // Prevent a physics force 
	DMG_NEVERGIB,       // with this bit OR'd in, no damage type will be able to gib victims upon death
	DMG_ALWAYSGIB,      // with this bit OR'd in, any damage type can be made to gib victims upon death.
	DMG_DROWN,          // Drowning


	DMG_PARALYZE,       // slows affected creature down
	DMG_NERVEGAS,       // nerve toxins, very bad
	DMG_POISON,         // blood poisoning - heals over time like drowning damage
	DMG_RADIATION,      // radiation exposure
	DMG_DROWNRECOVER,   // drowning recovery
	DMG_ACID,           // toxic chemicals or acid burns
	DMG_SLOWBURN,       // in an oven

	DMG_REMOVENORAGDOLL,// with this bit OR'd in, no ragdoll will be created, and the target will be quietly removed.
						// use this to kill an entity that you've already got a server-side ragdoll for

	DMG_PHYSGUN,        // Hit by manipulator. Usually doesn't do any damage.
	DMG_PLASMA,         // Shot by Cremator
	DMG_AIRBOAT,        // Hit by the airboat's gun

	DMG_DISSOLVE,       // Dissolving!
	DMG_BLAST_SURFACE,  // A blast on the surface of water that cannot harm things underwater
	DMG_DIRECT,
	DMG_BUCKSHOT,       // not quite a bullet. Little, rounder, different.

	DMG_BLAST,          // explosion
}

[Obsolete( "Damagables are done using DamageInfo and CoreDamageInfo" )]
public class TakeDamageInfo
{
	public Vector3 DamageForce { get; set; }
	public Vector3 DamagePosition { get; set; } //position players are told damage is coming from
	public Vector3 ReportedPosition { get; set; }
	public GameObject Inflictor { get; set; } //the weapon or rocket (or player) that is dealing the damage
	public GameObject Attacker { get; set; } //the character who originated the attack (like a player or an AI).
	public BaseCombatWeapon Weapon { get; set; } // the weapon that did the attack.
												 // For hitscan weapons, it'll be the same as the inflictor. For projectile weapons, the projectile 
												 // is the inflictor, and this contains the weapon that created the projectile.
	public float Damage { get; set; }
	public float BaseDamage { get; set; } //the damage amount before skill level adjustments are made, used to get uniform damage forces
	public int bitsType { get; set; }
	public Hitbox Hitbox { get; set; }

	public TakeDamageInfo()
	{
		DamageForce = Vector3.Zero;
		DamagePosition = Vector3.Zero;
		ReportedPosition = Vector3.Zero;
		Damage = 0f;
		BaseDamage = 0f;
		bitsType = 0;
	}
	public TakeDamageInfo( GameObject inflictor, GameObject attacker, float damage, DamageType type )
	{
		DamageForce = Vector3.Zero;
		DamagePosition = Vector3.Zero;
		ReportedPosition = Vector3.Zero;
		Inflictor = inflictor;
		Attacker = attacker;
		Damage = damage;

		AddDamageType( type );
	}
	public TakeDamageInfo( GameObject inflictor, GameObject attacker, BaseCombatWeapon weapon, float damage, DamageType type )
	{
		DamageForce = Vector3.Zero;
		DamagePosition = Vector3.Zero;
		ReportedPosition = Vector3.Zero;
		Inflictor = inflictor;
		Attacker = attacker;
		Weapon = weapon;
		Damage = damage;

		AddDamageType( type );
	}
	public TakeDamageInfo( GameObject inflictor, GameObject attacker, Vector3 damageForce, Vector3 damagePosition, float damage, DamageType type, Vector3 reportedPosition = new Vector3() )
	{
		DamageForce = damageForce;
		DamagePosition = damagePosition;
		ReportedPosition = reportedPosition;
		Inflictor = inflictor;
		Attacker = attacker;
		Damage = damage;

		AddDamageType( type );
	}
	//public TakeDamageInfo(GameObject inflictor, GameObject attacker, BaseWeapon weapon, Vector3 damageForce, Vector3 damagePosition, float damage, DamageType type, Vector3 reportedPosition = new Vector3()) { }

	public void AddDamageType( DamageType type ) { bitsType |= (1 << (int)type); }

	public bool HasDamageType( DamageType type ) { return (bitsType & (1 << (int)type)) != 0; }

	public void AdjustPlayerDamageTakenForSkillLevel() { } // TODO

	public void AdjustDamageScale( float scale )
	{
		if ( BaseDamage == 0f )
			BaseDamage = Damage;

		Damage = BaseDamage * scale;
	}
}

[Obsolete]
public delegate void OnTakeDamageAction( TakeDamageInfo DamageInfo );

[Obsolete( "Damagables are done using base Component.IDamagable" )]
public class TakeDamageController : Component
{
	[Property] public OnTakeDamageAction OnTakeDamage { get; set; }

	public void TakeDamage( TakeDamageInfo damageInfo )
	{
		//		dispatch action
		OnTakeDamage?.Invoke( damageInfo );
		//		distrubute to gameobjets
		//		GameObject.Components.Get<BasePlayer>()?.OnTakeDamage( damageInfo );

		if ( Tags.Has( "player_main" ) && GameObject.Parent != null )
			GameObject.Parent.Components.GetOrCreate<TakeDamageController>()?.TakeDamage( damageInfo );

		//		GameObject.Components.Get<BaseNpc>()?.OnTakeDamage( damageInfo );
		GameObject.Components.Get<Core.GameProp>()?.OnDamage( new DamageInfo( damageInfo.Damage, damageInfo.Attacker, damageInfo.Inflictor ) );

		//		if we have a ridid body add the damage force to it
		GameObject.Components.Get<Rigidbody>()?.PhysicsBody.ApplyImpulseAt( damageInfo.DamagePosition, damageInfo.DamageForce * 200f );
	}
}


public class DamageTagSet : TagSet
{
    [Description("Get all default tags for damage types.")]
    public override IEnumerable<string> GetSuggested()
    {
        // Return the predefined static damage tags
        return new[]
        {
            DamageTypes.DMG_GENERIC,
            DamageTypes.DMG_CRUSH,
            DamageTypes.DMG_BULLET,
            DamageTypes.DMG_SLASH,
            DamageTypes.DMG_BURN,
            DamageTypes.DMG_VEHICLE,
            DamageTypes.DMG_FALL,
            DamageTypes.DMG_CLUB,
            DamageTypes.DMG_SHOCK,
            DamageTypes.DMG_SONIC,
            DamageTypes.DMG_ENERGYBEAM,
            DamageTypes.DMG_PREVENT_PHYSICS_FORCE,
            DamageTypes.DMG_NEVERGIB,
            DamageTypes.DMG_ALWAYSGIB,
            DamageTypes.DMG_DROWN,
            DamageTypes.DMG_PARALYZE,
            DamageTypes.DMG_NERVEGAS,
            DamageTypes.DMG_POISON,
            DamageTypes.DMG_RADIATION,
            DamageTypes.DMG_DROWNRECOVER,
            DamageTypes.DMG_ACID,
            DamageTypes.DMG_SLOWBURN,
            DamageTypes.DMG_REMOVENORAGDOLL,
            DamageTypes.DMG_PHYSGUN,
            DamageTypes.DMG_PLASMA,
            DamageTypes.DMG_AIRBOAT,
            DamageTypes.DMG_DISSOLVE,
            DamageTypes.DMG_BLAST_SURFACE,
            DamageTypes.DMG_DIRECT,
            DamageTypes.DMG_BUCKSHOT,
            DamageTypes.DMG_BLAST
        };
    }
}
