namespace Core;

public enum LifeState
{
	Alive,
	Dead,
}
public readonly struct DamageTypes
{
	/// <summary>generic damage -- do not use if you want players to flinch and bleed! This is a catch-all damage type for when no other type fits. It has no special properties or interactions.</summary>
	public const string DMG_GENERIC = "generic";
	/// <summary>crushed by falling or moving object. 
	/// NOTE: It's assumed crush damage is occurring as a result of physics collision, so no extra physics force is generated by crush damage. 
	/// DON'T use DMG_CRUSH when damaging entities unless it's the result of a physics collision. You probably want DMG_CLUB instead.
	/// </summary>
	public const string DMG_CRUSH = "crush";
	/// <summary>shot</summary>
	public const string DMG_BULLET = "bullet";
	/// <summary>cut, clawed, stabbed</summary>
	public const string DMG_SLASH = "slash";
	/// <summary>heat burned</summary>
	public const string DMG_BURN = "burn";
	/// <summary>hit by a vehicle</summary>
	public const string DMG_VEHICLE = "vehicle";
	/// <summary>fell too far</summary>
	public const string DMG_FALL = "fall";
	/// <summary>crowbar, punch, headbutt</summary>
	public const string DMG_CLUB = "club";
	/// <summary>electric shock</summary>
	public const string DMG_SHOCK = "shock";
	/// <summary>sound pulse shockwave</summary>
	public const string DMG_SONIC = "sonic";
	/// <summary>laser or other high energy beam</summary>
	public const string DMG_ENERGYBEAM = "energybeam";
	/// <summary>Prevent a physics force</summary>
	public const string DMG_PREVENT_PHYSICS_FORCE = "nophysforce";
	/// <summary>with this bit OR'd in, no damage type will be able to gib victims upon death</summary>
	public const string DMG_NEVERGIB = "nevergib";
	/// <summary>with this bit OR'd in, any damage type can be made to gib victims upon death.</summary>
	public const string DMG_ALWAYSGIB = "alwaysgib";
	/// <summary>Drowning</summary>
	public const string DMG_DROWN = "drown";
	/// <summary>slows affected creature down</summary>
	public const string DMG_PARALYZE = "paralyze";
	/// <summary>nerve toxins, very bad</summary>
	public const string DMG_NERVEGAS = "nervegas";
	/// <summary>blood poisoning - heals over time like drowning damage</summary>
	public const string DMG_POISON = "poison";
	/// <summary>radiation exposure</summary>
	public const string DMG_RADIATION = "radiation";
	/// <summary>drowning recovery</summary>
	public const string DMG_DROWNRECOVER = "drownrecover";
	/// <summary>toxic chemicals or acid burns</summary>
	public const string DMG_ACID = "acid";
	/// <summary>in an oven</summary>
	public const string DMG_SLOWBURN = "slowburn";
	/// <summary>with this bit OR'd in, no ragdoll will be created, and the target will be quietly removed. use this to kill an entity that you've already got a server-side ragdoll for</summary>
	public const string DMG_REMOVENORAGDOLL = "removeonragdoll";

	/// <summary>Hit by manipulator. Usually doesn't do any damage.</summary>
	public const string DMG_PHYSGUN = "physgun";
	/// <summary>Shot by Cremator</summary>
	public const string DMG_PLASMA = "plasma";
	/// <summary>Hit by the airboat's gun</summary>
	public const string DMG_AIRBOAT = "airboat";
	/// <summary>Dissolving!</summary>
	public const string DMG_DISSOLVE = "dissolve";
	/// <summary>A blast on the surface of water that cannot harm things underwater</summary>
	public const string DMG_BLAST_SURFACE = "blastsurface";
	/// <summary></summary>
	public const string DMG_DIRECT = "direct";
	/// <summary>not quite a bullet. Little, rounder, different.</summary>
	public const string DMG_BUCKSHOT = "buckshot";
	/// <summary>explosion</summary>
	public const string DMG_BLAST = "blast";
}

// this is technically useless for now
/*
public class DamageHelpers
{
	public float Damage { get; set; }
	public float BaseDamage { get; set; } //	the damage amount before skill level adjustments are made, used to get uniform damage forces

	public void AdjustDamageScale( float scale )
	{
		if ( BaseDamage == 0f )
			BaseDamage = Damage;

		Damage = BaseDamage * scale;
	}
}*/


public class DamageTagSet : TagSet
{
	/// <summary>
	/// Get all default tags for damage types.
	/// </summary>
	/// <returns></returns>
	public override IEnumerable<string> GetSuggested()
	{
		// Return the predefined static damage tags
		return
		[
			DamageTypes.DMG_GENERIC,
			DamageTypes.DMG_CRUSH,
			DamageTypes.DMG_BULLET,
			DamageTypes.DMG_SLASH,
			DamageTypes.DMG_BURN,
			DamageTypes.DMG_VEHICLE,
			DamageTypes.DMG_FALL,
			DamageTypes.DMG_CLUB,
			DamageTypes.DMG_SHOCK,
			DamageTypes.DMG_SONIC,
			DamageTypes.DMG_ENERGYBEAM,
			DamageTypes.DMG_PREVENT_PHYSICS_FORCE,
			DamageTypes.DMG_NEVERGIB,
			DamageTypes.DMG_ALWAYSGIB,
			DamageTypes.DMG_DROWN,
			DamageTypes.DMG_PARALYZE,
			DamageTypes.DMG_NERVEGAS,
			DamageTypes.DMG_POISON,
			DamageTypes.DMG_RADIATION,
			DamageTypes.DMG_DROWNRECOVER,
			DamageTypes.DMG_ACID,
			DamageTypes.DMG_SLOWBURN,
			DamageTypes.DMG_REMOVENORAGDOLL,
			DamageTypes.DMG_PHYSGUN,
			DamageTypes.DMG_PLASMA,
			DamageTypes.DMG_AIRBOAT,
			DamageTypes.DMG_DISSOLVE,
			DamageTypes.DMG_BLAST_SURFACE,
			DamageTypes.DMG_DIRECT,
			DamageTypes.DMG_BUCKSHOT,
			DamageTypes.DMG_BLAST
		];
	}
}
